// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN9R-zNvN8qZ2SO7y4rLu5kwL1BRL_ehU',
    appId: '1:796925603688:web:126de4bf7094f5d80fb0dd',
    messagingSenderId: '796925603688',
    projectId: 'application-livora',
    authDomain: 'application-livora.firebaseapp.com',
    storageBucket: 'application-livora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1dAs3Z6iVzW2eawaLpnadC86GA_rp1U',
    appId: '1:796925603688:android:153ce24db2aaa8860fb0dd',
    messagingSenderId: '796925603688',
    projectId: 'application-livora',
    storageBucket: 'application-livora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnxdd9PwdpXbAL42usCJ4ecxE6YFrhBIA',
    appId: '1:796925603688:ios:a01082d845bc31d00fb0dd',
    messagingSenderId: '796925603688',
    projectId: 'application-livora',
    storageBucket: 'application-livora.firebasestorage.app',
    androidClientId: '796925603688-5lprk88iopc4c101vgjlhkrgrukf79uc.apps.googleusercontent.com',
    iosClientId: '796925603688-7ilf2994vs7qfmb3qkvltqike72c4sof.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnxdd9PwdpXbAL42usCJ4ecxE6YFrhBIA',
    appId: '1:796925603688:ios:a01082d845bc31d00fb0dd',
    messagingSenderId: '796925603688',
    projectId: 'application-livora',
    storageBucket: 'application-livora.firebasestorage.app',
    androidClientId: '796925603688-5lprk88iopc4c101vgjlhkrgrukf79uc.apps.googleusercontent.com',
    iosClientId: '796925603688-7ilf2994vs7qfmb3qkvltqike72c4sof.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN9R-zNvN8qZ2SO7y4rLu5kwL1BRL_ehU',
    appId: '1:796925603688:web:dd1c15e85e6f49aa0fb0dd',
    messagingSenderId: '796925603688',
    projectId: 'application-livora',
    authDomain: 'application-livora.firebaseapp.com',
    storageBucket: 'application-livora.firebasestorage.app',
  );

}